CREATE TABLE ZBOOK (
  Z_PK int(11) NOT NULL,
  Z_ENT int(11) DEFAULT NULL,
  Z_OPT int(11) DEFAULT NULL,
  ZCHAPTER_COUNT int(11) DEFAULT NULL,
  ZORDER int(11) DEFAULT NULL,
  ZSECTION int(11) DEFAULT NULL,
  ZNAME varchar(64) DEFAULT NULL,
  PRIMARY KEY (Z_PK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;