CREATE TABLE ZCONCORDANCE (
  Z_PK int(11) NOT NULL,
  Z_ENT int(11) DEFAULT NULL,
  Z_OPT int(11) DEFAULT NULL,
  ZOCCURANCES int(11) DEFAULT NULL,
  ZDICTIONARY int(11) DEFAULT NULL,
  ZVERSE int(11) DEFAULT NULL,
  ZENGLISH_WORD varchar(64) DEFAULT NULL,
  PRIMARY KEY (Z_PK),
  KEY ZCONCORDANCE_ZDICTIONARY_INDEX (ZDICTIONARY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;