CREATE TABLE ZVERSE (
  Z_PK int(11) NOT NULL,
  Z_ENT int(11) DEFAULT NULL,
  Z_OPT int(11) DEFAULT NULL,
  ZCHAPTER_NUM int(11) DEFAULT NULL,
  ZVERSE_NUM int(11) DEFAULT NULL,
  ZBOOK int(11) DEFAULT NULL,
  ZTEXT varchar(2048) DEFAULT NULL,
  ZTEXT_WITHOUT_EXTRAS varchar(2048) DEFAULT NULL,
  PRIMARY KEY (Z_PK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;